services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - C:/docker_data/BigDataSnowflake/data:/data
      - C:/docker_data/BigDataSnowflake/sql:/docker-entrypoint-initdb.d
      
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5